### ISSUE TITLE
About how SSIM parameters are calculated？

### ISSUE THREAD

**Issue by sqrtln** [AlienZhang1996/S2WAT#5]
```
from skimage.metrics import structural_similarity
import argparse
import matplotlib.pyplot as plt
import cv2
import os

parser = argparse.ArgumentParser()
parser.add_argument("--content_dir", required=False, default='./ssimcontent/', help="the directory of content images")
parser.add_argument("--stylized_dir", required=False, default='./styleedImage/', help="the directory of stylized images")
args = parser.parse_args()

content_dir = args.content_dir
stylized_dir = args.stylized_dir

stylized_files = os.listdir(stylized_dir)

ssim_sum = 0.
count = 0

for stylized in stylized_files:
    stylized_img = cv2.imread(stylized_dir + stylized) 
    name = stylized.split("_")  
    content_img = cv2.imread(content_dir + name[0] + '.jpg')

    grayA = cv2.cvtColor(content_img, cv2.COLOR_BGR2GRAY)
    grayB = cv2.cvtColor(stylized_img, cv2.COLOR_BGR2GRAY)
    (score, diff) = structural_similarity(grayA, grayB, full=True)

    print("SSIM: {}".format(score))
    ssim_sum += score
    count += 1

print("Total num: {}".format(count))
print("Average SSIM: {}".format(ssim_sum / count))
plt.imshow(diff, cmap=plt.cm.gray)
plt.colorbar()
plt.show()

``` 
this is my cal code , I used the model you provided to generate the image after stylization, and the original content image as input for calculating SSIM, and I got a value of only 0.368, and the SSIM value you provided in your paper is 0.651, which is a bit big difference.I'm wondering if my math is different than yours.  ths~

Attached below are the two pictures I used to calculate SSIM.

Content Image:
![image](https://github.com/AlienZhang1996/S2WAT/assets/133953561/64fb499e-c328-4c0d-a3a2-ea36e34d0969)

Style Image:
![image](https://github.com/AlienZhang1996/S2WAT/assets/133953561/932817a1-a0a6-4ac4-b2bd-40ee3aac838d)

Result
![image](https://github.com/AlienZhang1996/S2WAT/assets/133953561/90086b9e-4c9f-41f5-be0f-1259756f04c1)

![image](https://github.com/AlienZhang1996/S2WAT/assets/133953561/6407a7fa-303a-44d4-966f-1deae270428a)
![image](https://github.com/AlienZhang1996/S2WAT/assets/133953561/b911bebe-f0d8-4e19-afcb-b78c538f6a8d)

![ssim](https://github.com/AlienZhang1996/S2WAT/assets/133953561/10c8aa36-be25-4e7f-a6b0-94c13658a3e0)

**Comment by AlienZhang1996** [comment]
Dear tuan,

I am sorry for the ambiguity in our use of the term SSIM. We actually use
MS-SSIM, which considers SSIM scores at different resolutions with greater
flexibility. For more details, please refer to the paper
<https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1292216>or the
code <https://github.com/jorge-pessoa/pytorch-msssim/tree/master>.

Best regards,

Chiyu Zhang

tuan ***@***.***> 于2024年7月5日周五 17:00写道：

**Comment by sqrtln** [comment]
Thx for the answer, I think that had made an error in my cals. By the way,we have a junior sister in our laboratory,  who's an undergrad alum of yours.
